-- Phase 12.4: Update Pricing Plans - developing (6 records)
UPDATE service_pricing_plans SET plan_name = 'MVP Build', plan_subtitle = 'Core features delivered', price_amount = 999, features = '["Core module implementation","Data model alignment","Auth-ready integration path","Baseline test coverage","Deployment readiness support"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '5e9ba1e2-5c50-4044-9e2f-0441e4e494b4';
UPDATE service_pricing_plans SET plan_name = 'Production Build', plan_subtitle = 'Reliability-first delivery', price_amount = 1999, features = '["Integration engineering support","Error handling + logging plan","Performance baseline checks","QA and stabilization pass","Release governance checklist"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '66bb2127-0d7d-435d-894f-d745862806ea';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Build', plan_subtitle = 'High-security systems', price_amount = 3499, features = '["Security hardening baseline","Multi-module architecture","Compliance-ready practices","Optimization and load review","Priority support window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '164132e3-4af1-42ac-aa6d-febfd547fb02';
UPDATE service_pricing_plans SET plan_name = 'MVP Annual', plan_subtitle = 'Build + continuous care', price_amount = 9999, features = '["Roadmap planning support","Ongoing fixes and tuning","Quarterly QA checkpoints","Performance review cadence","Documentation upkeep"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'e374629f-f56a-45e8-9cc1-25046f1a5460';
UPDATE service_pricing_plans SET plan_name = 'Production Annual', plan_subtitle = 'Operate at scale', price_amount = 19999, features = '["Stabilization retainer","Integration expansion support","Security review checkpoints","Release governance support","Priority support channel"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '80d9e93e-1797-46b1-8dc9-767228cf9e11';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Annual', plan_subtitle = 'Mission-critical ops', price_amount = 34999, features = '["Operational stewardship model","Incident readiness guidance","Hardened release workflow","Audit-ready documentation","Dedicated support cadence"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '23c7aadb-36e8-4fc4-bbc7-e0af05021616';

-- Phase 12.4: Update Pricing Plans - graphic-design (6 records)
UPDATE service_pricing_plans SET plan_name = 'Brand Starter', plan_subtitle = 'Essential identity assets', price_amount = 499, features = '["Brand direction session","Core identity assets","Social template starter set","Usage guidance basics","Delivery files organized"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '4ea797af-5a09-41bc-a473-2705af42d253';
UPDATE service_pricing_plans SET plan_name = 'Brand System', plan_subtitle = 'Full brand consistency', price_amount = 999, features = '["Visual system definition","Template set expansion","Messaging alignment support","Brand checks for key assets","Handoff documentation pack"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '7d42fe3c-1dd1-498c-a519-618fc5109054';
UPDATE service_pricing_plans SET plan_name = 'Brand Enterprise', plan_subtitle = 'Multi-channel rollout', price_amount = 1799, features = '["Extended brand guidelines","Multi-team rollout support","Asset governance approach","Production-ready templates","Priority revisions window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '75f1a72a-3633-4deb-ba4a-e1915ba604a0';
UPDATE service_pricing_plans SET plan_name = 'Starter Annual', plan_subtitle = 'Ongoing brand support', price_amount = 4999, features = '["Quarterly brand refresh cycle","New asset creation blocks","Campaign template support","Consistency review cadence","Priority turnaround channel"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '02538891-64ae-4355-84b5-be3b38ae6358';
UPDATE service_pricing_plans SET plan_name = 'System Annual', plan_subtitle = 'Maintain brand standards', price_amount = 9999, features = '["Template library growth","Multi-channel brand QA","Guidance documentation upkeep","Collaboration review sessions","Priority revisions window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '3c7e6920-8776-48c6-a3bd-4a82dc379f4a';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Annual', plan_subtitle = 'Full brand governance', price_amount = 17999, features = '["Brand governance framework","High-volume asset production","Cross-team alignment support","Rollout planning assistance","Dedicated support cadence"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '5b2ba80e-b4e5-4b3b-8947-693d5f2c376d';

-- Phase 12.4: Update Pricing Plans - video-animation (6 records)
UPDATE service_pricing_plans SET plan_name = 'Explainer Starter', plan_subtitle = 'Clear message delivery', price_amount = 599, features = '["Script outline support","Motion style direction","One core video deliverable","Caption-ready formatting","Export in key formats"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'e090b9ac-3c1b-477c-99af-a43d021660c9';
UPDATE service_pricing_plans SET plan_name = 'Campaign Motion', plan_subtitle = 'Multi-asset package', price_amount = 1199, features = '["Creative direction session","Multiple motion assets set","Cut-down variants included","Brand-consistent visuals","Review and polish cycle"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '6c91c50c-c393-4832-abed-6a7c55190a02';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Media', plan_subtitle = 'High-volume delivery', price_amount = 2199, features = '["Multi-format deliverables","Production workflow planning","Faster revision turnaround","Asset library organization","Priority delivery window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'ac949938-d3b1-4abc-989b-59f172652c16';
UPDATE service_pricing_plans SET plan_name = 'Starter Annual', plan_subtitle = 'Continuous media output', price_amount = 5999, features = '["Quarterly media planning","Ongoing content releases","Cut-down variants included","Brand consistency checks","Priority turnaround channel"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '796dec0d-8e83-4b2e-bc7c-8b89bec5243d';
UPDATE service_pricing_plans SET plan_name = 'Campaign Annual', plan_subtitle = 'Motion for growth', price_amount = 11999, features = '["Monthly asset allocations","Multi-platform export support","Review and polish cadence","Creative direction sessions","Priority delivery window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'd6719e2e-a99f-48af-acf6-88e9ba33dae2';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Annual', plan_subtitle = 'Media operations support', price_amount = 21999, features = '["High-volume production blocks","Workflow governance support","Quality control checkpoints","Asset library management","Dedicated support cadence"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '23085904-71b0-4c40-9d92-e35763412b7e';

-- Phase 12.4: Update Pricing Plans - 3d-design (6 records)
UPDATE service_pricing_plans SET plan_name = '3D Starter', plan_subtitle = 'Core renders package', price_amount = 699, features = '["Reference and scene planning","3D model and render setup","Core render deliverables","Revision round included","Web-ready exports provided"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '2fb7d993-dbc5-4d2c-ac2b-d72e90fcd456';
UPDATE service_pricing_plans SET plan_name = '3D Pro', plan_subtitle = 'Multi-angle visuals', price_amount = 1399, features = '["Multi-angle render set","Higher detail refinement","Presentation-ready outputs","Variant exports included","Quality review checkpoints"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'c2cba115-7111-407b-a1d3-6c80d970c7ef';
UPDATE service_pricing_plans SET plan_name = '3D Enterprise', plan_subtitle = 'Complex scene delivery', price_amount = 2499, features = '["Complex scenes supported","Extended render variants set","Priority revision window","Asset organization guidance","Delivery workflow support"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'c72230de-89ea-481e-9619-10a1e884ff73';
UPDATE service_pricing_plans SET plan_name = 'Starter Annual', plan_subtitle = 'Ongoing render output', price_amount = 6999, features = '["Quarterly render allocations","Consistent visual standards","Variant exports included","Review and polish cadence","Priority turnaround channel"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '27bbee6b-1a1c-42ab-9d23-d13df836f5d0';
UPDATE service_pricing_plans SET plan_name = 'Pro Annual', plan_subtitle = 'Visual pipeline retained', price_amount = 13999, features = '["Monthly production blocks","Quality control checkpoints","Presentation-ready outputs","Asset management support","Priority revision window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '33a176a8-0d9d-4398-85f4-9b1f82c64094';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Annual', plan_subtitle = 'High-volume 3D ops', price_amount = 24999, features = '["Complex scenes supported","Extended render variants set","Workflow governance support","Library organization included","Dedicated support cadence"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'bee6681e-be5e-4816-89c1-18b353145ff3';

-- Phase 12.4: Update Pricing Plans - ui-ux-design (6 records)
UPDATE service_pricing_plans SET plan_name = 'Service Sprint', plan_subtitle = 'Map and validate fast', price_amount = 799, features = '["Workflow mapping session","Service flow documentation","UX screens for 1 journey","Validation and findings","Implementation guidance pack"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '304b6c72-d528-4f65-8224-cb2b7246fbe5';
UPDATE service_pricing_plans SET plan_name = 'Service Blueprint', plan_subtitle = 'Full workflow coverage', price_amount = 1599, features = '["Multi-role flow coverage","Service blueprint creation","UX screens + states pack","Validation checkpoints","Design-dev alignment notes"]'::jsonb, cta_label = 'Get a Quote' WHERE id = 'aebe8945-af38-49a7-bdfa-88ddf242e9dc';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Service', plan_subtitle = 'Complex operations design', price_amount = 2899, features = '["Multi-module workflow design","Governance-ready documentation","Accessibility considerations","QA support for build phase","Priority iteration window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '063f5f67-02fd-4c4c-9a80-9f39cc66b40d';
UPDATE service_pricing_plans SET plan_name = 'Sprint Annual', plan_subtitle = 'Continuous workflow tuning', price_amount = 7999, features = '["Quarterly flow improvements","Validation touchpoints","New journey additions","Documentation upkeep","Priority support channel"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '1f7055ec-ec31-4619-9b56-4c3f5604885d';
UPDATE service_pricing_plans SET plan_name = 'Blueprint Annual', plan_subtitle = 'Operate with clarity', price_amount = 15999, features = '["Service governance support","Continuous UX iteration","Multi-role updates included","QA checkpoints quarterly","Priority iteration window"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '24a614de-4b8f-4609-99a0-1d1e97b33e87';
UPDATE service_pricing_plans SET plan_name = 'Enterprise Annual', plan_subtitle = 'Mission-critical services', price_amount = 28999, features = '["Workflow governance framework","Complex ops design retained","Audit-ready documentation","Release alignment support","Dedicated support cadence"]'::jsonb, cta_label = 'Get a Quote' WHERE id = '936cb4c2-de78-495f-bc58-2c02636ea58a';